//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("0.0.0001.0")]
[assembly: AssemblyFileVersion("0.0.0001.0")]
[assembly: AssemblyCompany("dev.IL engineering")]
[assembly: AssemblyCopyright("Copyright © dev.IL engineering 2012")]
[assembly: AssemblyProduct("SSMSHistorizer")]
[assembly: AssemblyTrademark("https://github.com/kimpenhaus/SSMSHistorizer")]